### ISSUE TITLE
Fill out README with explanation and examples

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/FEniCS.jl#25]

**Comment by ChrisRackauckas** [comment]
Can we cleanup the README a little bit? Links can be added directly onto relevant text using the markdown syntax `[text](link)`, so things like ParaView should include the link on it. There should be a small block which is a working example that someone can copy-paste to know it works. Then, for this project, we should probably have a list of links with appropriate titles to Gists which go more in depth.

**Comment by ChrisRackauckas** [comment]
If you want to instead add some pictures, a good way to do that is to make (and close) an issue, and drop the pictures into there. Then you can link to them in a way that won't increase the repo size.

**Comment by ysimillides** [comment]
#30
