### ISSUE TITLE
Single quotes in README example are not valid Julia

### ISSUE THREAD

**Issue by rodrigolece** [JuliaDiffEq/FEniCS.jl#38]
The line `vtkfile = File('poisson/solution.pvd')` has Python quotes, to make it valid Julia you should change this to double quotes. I'm just being picky here but since it's the introductory example, a complete newbie (to Julia) might not know what's wrong.

Also, guys!! Amazing job!! Julia is my favourite language but it's been a while since I can use it in my research. I see so much development of the libraries, including yours, that I will be pushing now to be a Julian again :)

**Comment by ChrisRackauckas** [comment]
Yup oops. Thanks for the report.
