### ISSUE TITLE
README plots aren't working

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/FEniCS.jl#39]
@ysimillides just post them into this issue and link to them.

**Comment by ysimillides** [comment]
![mesh](https://user-images.githubusercontent.com/16087601/34915337-b2c0aede-f91c-11e7-986a-5658d23c262e.png)
![solution](https://user-images.githubusercontent.com/16087601/34915339-b77e8694-f91c-11e7-9ae1-db1e114a177a.png)
