### ISSUE TITLE
Abstract the Python FFI from the API

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/FEniCS.jl#4]
There are still a few points where the API is relying on the Python calls. Those should be abstract away. For example:

https://github.com/JuliaDiffEq/FEniCS.jl/blob/master/test/test_create.jl#L17
https://github.com/JuliaDiffEq/FEniCS.jl/blob/master/test/test_create.jl#L18

the user shouldn't need to know to dig into `fenics` to use `Point`: you should take in a `tuple` and convert it to a `Point` inside the function call.

**Comment by ysimillides** [comment]
This has been fixed. Point is now a function , and takes vector inputs
