### ISSUE TITLE
Symbols instead of strings

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/FEniCS.jl#5]
Small API point, but symbols are normally used in Julian APIs because comparisons are easier (and they generate nicer typed code, amongst other things). So instead of `"left"`, the user-exposed API should expect `:left`. You can then internally call `string(x)` to turn it into a string to pass to Python.

**Comment by ysimillides** [comment]
Type has been changed to Union{String,Symbol}. This allows *pure* Julia users to use :left ,while allowing FEniCS users to still use "left".
