### ISSUE TITLE
Plotting issue

### ISSUE THREAD

**Issue by jw3126** [JuliaDiffEq/FEniCS.jl#69]
Can we have better plotting instructions in the README? I am willing do provide a PR, if you tell me a recomended way of plotting.
Just doing `FEniCS.Plot(U)` merely displays `PyObject <matplotlib.tri.tricontour.TriContourSet object at 0x7f3e802bd630>` for me.

In order to get a plot I can do
```julia
using PyCall
using FEniCS
plt = pyimport("matplotlib").pyplot
FEniCS.Plot(U)
plt.show()
```
Is that the intended way to do things?

**Comment by ChrisRackauckas** [comment]
Interesting. Does PyPlot.jl work for you?

**Comment by jw3126** [comment]
Yeah it works 
```julia
using PyPlot
plot(randn(10), randn(10))
```
displays some random line plot without issues.

**Comment by ChrisRackauckas** [comment]
Oh wait, yes I misread you. The `plt.show()` command should be added to the README.
