### ISSUE TITLE
OSX Brew install issues on Travis

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/FEniCS.jl#78]
Looks like Travis Mac is just failing at the Homebrew stage? 

https://travis-ci.org/JuliaDiffEq/FEniCS.jl/jobs/613067106

@ararslan, @staticfloat and @StefanKarpinski do you have any idea how to make it use a newer Ruby for this?

**Comment by ChrisRackauckas** [comment]
@sjkelly when you added the Mac CI it didn't fail, so are you familiar with what happened to the Julia Travis setup change that caused this failure?

**Comment by staticfloat** [comment]
Try asking for a newer Xcode image, [that sets the MacOS version](https://docs.travis-ci.com/user/reference/osx/#macos-version), which itself informs the system ruby version.

**Comment by ChrisRackauckas** [comment]
Awesome https://github.com/JuliaDiffEq/FEniCS.jl/pull/79
