### ISSUE TITLE
Get CI working

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/FEniCS.jl#9]
High on the priority list is to get CI working. I am not sure how, but we should check what the other FEniCS.jl had to do to make it work.

**Comment by ysimillides** [comment]
Noted. I will look at how travis is generally set to work, and look at adapting it to our problem. I'll probably try and do this throughout the downtime at JuliaCon if possible.

________________________________

**Comment by ChrisRackauckas** [comment]
I'll take a look at this right now and see what I can do.

**Comment by ChrisRackauckas** [comment]
https://travis-ci.org/JuliaDiffEq/FEniCS.jl/jobs/244237546#L236

Travis has my problem...

**Comment by ChrisRackauckas** [comment]
Looks like it could be a Python2 vs Python3 problem? FEniCS is Python 3 ?

**Comment by ysimillides** [comment]
Regarding CI, AppVeyor is mainly (only?) for windows if I'm not mistaken. Should we remove it completely?

**Comment by ChrisRackauckas** [comment]
Yes. Add to the README that we won't even hope for Windows to work anytime soon and just move on.

**Comment by ysimillides** [comment]
@ChrisRackauckas has setup Continuous Integration.
